train_selfsup_mr:
    name: [KITTI]
    path: [/beegfs/work/shared/kitti/Raw_data]
    split: [/beegfs/work/shared/kitti_eigen_split/splits/train_files.txt]
    augmentation:
        jittering: [0.2, 0.2, 0.2, 0.05]
        resize: [192, 640]
    dataloader:
        batch_size: 12
        pin_memory: True
        num_workers: 16
    context: [-1,1]
    labels: []
    cameras: [[0]]
    single_intrinsics: [True]
    repeat: [1]
validation_mr:
    name: [KITTI]
    path: [/beegfs/work/shared/kitti/Raw_data]
    split: [/beegfs/work/shared/kitti_eigen_split/splits/val_files.txt]
    augmentation:
        resize: [192, 640]
    dataloader:
        batch_size: 1
        pin_memory: True
        num_workers: 16
    context: []
    labels: [depth]
    cameras: [[0]]
    single_intrinsics: [True]
    depth_type: [depth_improved]
test_mr:
    name: [KITTI]
    path: [/beegfs/work/shared/kitti/Raw_data]
    split: [/beegfs/work/shared/kitti_eigen_split/splits/test_files.txt]
    augmentation:
        resize: [192, 640]
    dataloader:
        batch_size: 1
        pin_memory: True
        num_workers: 16
    context: []
    labels: [depth]
    cameras: [[0]]
    single_intrinsics: [True]
    depth_type: [depth, depth_improved]
