pip install torch torchvision --extra-index-url https://download.pytorch.org/whl/cu113
pip install tqdm==4.61.0
pip install boto3==1.17.83
pip install termcolor==1.1.0
pip install pyyaml==5.4.1
pip install wandb==0.10.31
pip install opencv-python==4.5.2.52
pip install flow_vis==0.1
pip install matplotlib==3.3.4
pip install fire==0.4.0
pip install pyquaternion==0.9.9
pip install pandas==1.1.5
pip install xarray==0.16.2
pip install diskcache==5.2.1
pip install tenacity==7.0.0
pip install pycocotools==2.0.2
pip install awscli==1.19.101
pip install ref==0.0.2.2
pip install positional-encodings==4.0.0
pip install einops
pip install wget
pip install ftfy
pip install regex
pip install tqdm
pip install pygame==2.0.1
pip install PyOpenGL==3.1.5
pip install PyOpenGL-accelerate==3.1.5
pip install pytorch3d
pip install lpips
pip install wget
pip install scikit-image
pip install pyhocon
pip install dotmap
pip install path
pip install sacremoses
pip install filelock
pip install huggingface_hub
pip install cupy
pip install torch-scatter
