wrapper:
    recipe: wrapper|default
    max_epochs: 1
arch:
    model:
        file: depth/DepthFormerModel
        warp_context: [ -1,1 ]
        match_context: [ -1 ]
        motion_masking: True
        matching_augmentation: False
        freeze_teacher_and_pose: 45
    networks:
        transformer:
            recipe: networks/transformer|depthformer
        mono_depth:
            recipe: networks/mono_depth_res_net|default
            depth_range: [0.1,100.0]
        multi_depth:
            recipe: networks/multi_depth_res_net|depthformer
        pose:
            recipe: networks/pose_net|default
    losses:
        reprojection:
            recipe: losses/reprojection|default
        smoothness:
            recipe: losses/smoothness|default
        supervision:
            recipe: losses/supervised_depth|l1
evaluation:
    depth:
        recipe: evaluation/depth|kitti_resize

optimizers:
    multi_depth:
        recipe: optimizers|adam_20_05
    mono_depth:
        recipe: optimizers|adam_20_05
    pose:
        recipe: optimizers|adam_20_05
    transformer:
        recipe: optimizers|adam_20_05
datasets:
    train:
        recipe: datasets/kitti_tiny|train_selfsup_mr
        labels: [pose]
        context: [ -1,1 ]
    validation:
        recipe: datasets/kitti_tiny|validation_mr
        labels: [ depth,pose ]
        context: [ -1,1 ]

save:
    recipe: save|depth_splitname