wrapper:
    recipe: wrapper|default
arch:
    model:
        file: depth/DepthFormerModel
        warp_context: [-1,1]
        match_context: [-1]
        motion_masking: True
        matching_augmentation: False
        freeze_teacher_and_pose: 40
        checkpoint: overwrite this via cmd args!
    networks:
        transformer:
            recipe: networks/transformer|depthformer
        mono_depth:
            recipe: networks/mono_depth_res_net|default
            depth_range: [0.1,100.0]
        multi_depth:
            recipe: networks/multi_depth_res_net|depthformer
        pose:
            recipe: networks/pose_net|default
evaluation:
    depth:
        recipe: evaluation/depth|kitti_resize
datasets:
    validation:
        recipe: datasets/kitti|validation_mr
        labels: [depth]
        context: [-1,1]
        depth_type: [depth, depth_improved]
        augmentation:
            resize: [128, 416]
save:
    recipe: save|depth_splitname
wandb:
    folder: data/wandb     # Where the wandb run is stored
    entity: js0           # Wandb entity
    project: depthformer         # Wandb project
    name: pretrained_inference_lr
